
// import './globals.css'
import React from "react";
import Head from 'next/head'

// components

import Navbar from "../Navbars/IndexNavbar";
import Footer from "../Footers/Footer";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Block-Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <section className="absolute inset-y-40 left-0 z-10  items-center  w-full  h-auto		 ">

          {children}
        </section>

      </main>
      <Footer />

    </>
  );
}

